### PR TITLE
Redesign main nav on desktop

### PR DESCRIPTION
**Pull request by trishalim**
- add nav items under "docs" in popover
- remove social links (nav was too crowded), replace with one CTA to join discord
- no changes to mobile menu

### CODE REVIEW

**Comment by gdorsi** [comment]
Aligned with main to add a timeout to the "Jazz-run" action that otherwise could be stuck for 5 hours after a commit

**Review by aeplay — CHANGES_REQUESTED** [review]
Sorry, only had a chance to look at this now. Looks great! Can we make it open on hover please?

**Comment by aeplay** [comment]
Furthermore: I like the prominent Discord button, but can we make the font in it a bit smaller and reintroduce GitHub and Twitter? And maybe the discord button can have a logo? It's ok for it to be a bit more crowded, they are all important

**Comment by trishalim** [comment]
Thanks for the feedback

I will change this to use shadcn/radix. Their popovers open on hover.

As for the social icons, I'll put these back where they were before.

**Comment by trishalim** [comment]
@aeplay do you mind if I do the open on hover separately?

I'm not liking my current [PR](https://github.com/gardencmp/jazz/pull/750) for it, but it would great to have some progress on the docs this week (currently there is none), and I'm preoccupied with [this](https://github.com/gardencmp/jazz/pull/748). If we merge this (after I put the social icons) back, then I can make separate pages for examples and api ref.

**Comment by aeplay** [comment]
> @aeplay do you mind if I do the open on hover separately?
> 
> I'm not liking my current [PR](https://github.com/gardencmp/jazz/pull/750) for it, but it would great to have some progress on the docs this week (currently there is none), and I'm preoccupied with [this](https://github.com/gardencmp/jazz/pull/748). If we merge this (after I put the social icons) back, then I can make separate pages for examples and api ref.

ok, merging! @trishalim

**Pull request merged**
