### PR TITLE
Rename CoStream to CoFeed

### PR DESCRIPTION
**Pull request by marinoska**

### CODE REVIEW

**Review by gdorsi — COMMENTED** [review]
Would it be possible to export `CoStream` as an alias?

Otherwise this would be technically a breaking change.

**Comment by marinoska** [comment]
> Would it be possible to export `CoStream` as an alias?
> 
> Otherwise this would be technically a breaking change.

Why not, really?

**Comment by marinoska** [comment]
> Would it be possible to export `CoStream` as an alias?
> 
> Otherwise this would be technically a breaking change.

For sure

**Comment by marinoska** [comment]
@aeplay What about BinaryCoStream?

**Comment by gdorsi** [comment]
> @aeplay What about BinaryCoStream?

Maybe we should rename them into "FileStream"?

**Review by aeplay — APPROVED** [review]
Perfect, thanks for the graceful deprecation / backwards-compatibility!

**Comment by aeplay** [comment]
> @aeplay What about BinaryCoStream?

I'd say BinaryStream - as it can also be used for ongoing livestreams, not just finite files (cc @marinoska  @gdorsi)

**Comment by gdorsi** [comment]
> > @aeplay What about BinaryCoStream?
> 
> I'd say BinaryStream - as it can also be used for ongoing livestreams, not just finite files (cc @marinoska @gdorsi)

The most common usage would be related to files and I think that using the "File" prefix helps with discoverabilty (one should be able to find and use it with just the TS declarations without looking at the docs).

For livestreams we can do an alias or another view type. I think that would give the feeling of a more solid support from our side.

**Comment by marinoska** [comment]
> > > @aeplay What about BinaryCoStream?
> > 
> > 
> > I'd say BinaryStream - as it can also be used for ongoing livestreams, not just finite files (cc @marinoska @gdorsi)
> 
> The most common usage would be related to files and I think that using the "File" prefix helps with discoverabilty (one should be able to find and use it with just the TS declarations without looking at the docs).
> 
> For livestreams we can do an alias or another view type. I think that would give the feeling of a more solid support from our side.

@aeplay wdyt?

**Comment by aeplay** [comment]
@marinoska @gdorsi OK, let's go with FileStream for now and invent a new view when we actually have high-level conveniences for live streaming

**Pull request merged**
