### PR TITLE
Docs outline, move guide pages to right side nav

### PR DESCRIPTION
**Pull request by trishalim**
- define a rough outline for the docs (in `/lib/docNavigationItems` which is commented out for now)
- redesign the layout so that it's ready to have more pages

### CODE REVIEW

**Comment by trishalim** [comment]
image
This level should be hidden unless you're on "intro to covalues" page
I need to put each of those in separate routes first @aeplay

**Comment by trishalim** [comment]
@aeplay I moved Guide under Getting Started. And the items inside it are now on the right side. 
image
It's squished. Will continue tomorrow.

**Comment by trishalim** [comment]
@aeplay 
image


I removed the empty pages from the nav so we can merge this
image

**Comment by trishalim** [comment]
@aeplay 
image


I removed the empty pages from the nav so we can merge this
image

**Comment by trishalim** [comment]
@aeplay I rearranged the proposed outline to cover more of what's already in the guide. The big question mark here for me is how to show separate the react and react native guide. Maybe first version could be just for react, and we link to the react-native readme?

**Comment by aeplay** [comment]
Let's discuss here: https://jazz-homepage-git-trishalim-jazz-388-gcmp.vercel.app/docs

**Pull request merged**
