### PR TITLE
Rename Jazz Mesh to Jazz Cloud

### LINKED ISSUE #545: Rename Jazz Mesh to Jazz Cloud

### PR DESCRIPTION
**Pull request by bensleveritt**
Replaces all instances of sync.jazz.tools or mesh.jazz.tools with cloud.jazz.tools. Updates the docs accordingly

### CODE REVIEW

**Comment by trishalim** [comment]
@bensleveritt Thanks! I didn't find anything else that needed changing (aside from the diagram. did it in another PR)

**Comment by bensleveritt** [comment]
Looks like we'll need the cloud dns for the tests to pass. And the books-demo is failing to deploy @aeplay

**Review by trishalim — APPROVED** [review]

**Comment by aeplay** [comment]
Ok I actually created the cloud.jazz.tools web socket alias - @bensleveritt please may you sort out the merge conflicts and then we'll see if the tests pass now?

**Comment by aeplay** [comment]
Thank you very much!

**Pull request merged**
