### PR TITLE
Redesign UI of docs side nav

### PR DESCRIPTION
**Pull request by trishalim**
todo: move to design system

### CODE REVIEW

**Comment by trishalim** [comment]
@aeplay It's not done but feel free to review

I'm also going to get the design system app running so that I can make a style guide [like this](https://www.lawschooltransparency.com/styleguide) and put `SideNav` component there

**Comment by trishalim** [comment]
@aeplay On second thought, I'm not adding this to the design system because it's very specific to the docs especially the section with the API references.

**Comment by aeplay** [comment]
Looks really nice!!
Only one issue remaining in Safari which still shows the built-in detail expander arrows:

Screenshot 2024-09-24 at 09 08 41

Edit: fixed it quickly

**Review by aeplay — APPROVED** [review]

**Comment by trishalim** [comment]
@aeplay Thanks for the fix 🙏

**Pull request merged**
