### PR TITLE
Simplify pricing

### PR DESCRIPTION
**Pull request by aeplay**

### CODE REVIEW

**Comment by trishalim** [comment]
I'm working on styling

**Comment by trishalim** [comment]
@aeplay I made some commits, so please pull when working on this again.

**Comment by trishalim** [comment]
Let's dial back on describing the users, and start with describing what they get from us

- ﻿Everything you need to kickstart your brand new project
- Self-serve our proven real-time infra for your growing product (though it's unclear to me what "self-serve" and "proven" means here)
- Dedicated support, infrastructure, and development to get you moving quickly

**Comment by trishalim** [comment]
The first CTA looks disabled, and the alert behavior is weird.

The second CTA looks disabled but it's not? 

I suggest you change both to use the secondary button variant. Try using the medium button sizes for all the CTA as well and see if that looks better. This is getting quite long for my screen now.

image

**Comment by aeplay** [comment]
Addressed your feedback and reduced vertical height a bit more.

The "Get Started" alert behaviour is a placeholder - once we merge your docs intro PR I'll probably add a disclaimer there for the interim API keys and then have the button link to that

**Comment by trishalim** [comment]
@aeplay Great! One last thing, can you move back the text under the CTA? And then I think it's all good
image

**Review by trishalim — APPROVED** [review]

**Pull request merged**
