### PR TITLE
Replaces github url with new one

### PR DESCRIPTION
**Pull request by bensleveritt**
Find and replace `github.com/gardencmp` with `github.com/garden-co`

### CODE REVIEW

**Comment by trishalim** [comment]
Great! Thanks. There are also lots of `gcmp.io` that can be `garden.co`. The website links we can change for sure, but I don't know about the email addresses.

**Review by trishalim — APPROVED** [review]

**Comment by aeplay** [comment]
The email adresses anselm@garden.co and hello@garden.co should work so you can change those too

**Comment by aeplay** [comment]
And please fix merge conflicts, thx

**Comment by bensleveritt** [comment]
@aeplay 
Should I change the cloud keys too?

**Pull request merged**
