### PR TITLE
Emphasize invite link to join chat in chat example

### PR DESCRIPTION
**Pull request by trishalim**
image

### CODE REVIEW

**Comment by aeplay** [comment]
I actually really like this. I have some ideas for the next iteration but right now this separates the app from the surroundings very nicely. And I like the updated styling and how you're making things more consistent with each other

**Comment by trishalim** [comment]
Thanks @aeplay 
Do you think the invite link is clear now?

**Comment by aeplay** [comment]
> Thanks @aeplay Do you think the invite link is clear now?

yes! Was there anything else you wanted to do in this PR? Happy for you to take it out of draft

**Comment by trishalim** [comment]
@aeplay I have to do mobile view and check dark mode

I need to hide the invite bar if there is no chat created
image

**Comment by aeplay** [comment]
So one thing I liked before is that it looked like a little browser. Do you think there's a way to keep the URL in a little URL bar thing, and then once you create a chat maybe have a little note pop up that calls out the shareability of the link?

If that sounds like too much work for this PR, it's fine as is

**Comment by trishalim** [comment]
@aeplay ok will think on that. For now there's some css I'm fixing.

**Comment by trishalim** [comment]
@aeplay what about this?
image

**Comment by aeplay** [comment]
@trishalim love it. Can we make the hint appear only if the URL contains "/#/chat/..."? That way it would pop up on chat creation in a way that draws attention I think

**Comment by trishalim** [comment]
@aeplay great idea! now it's super obvious

**Pull request merged**
