### PR TITLE
Add homepage to pnpm workspace

### LINKED ISSUE #495: Homepage dependencies not installed on fresh install
npm packages aren't installed as part of \`pnpm i\`, as it's missing from the pnpm workspace

### PR DESCRIPTION
**Pull request by bensleveritt**

### CODE REVIEW

**Comment by gdorsi** [comment]
I'm not sure why it wasn't part of the workspace before, maybe for deploy reasons?

I think it's better to wait for @aeplay review so he can give us some historical context.

**Comment by gdorsi** [comment]
@bensleveritt 

The build in the CI is failing: https://github.com/gardencmp/jazz/actions/runs/11219737794/job/31186358715?pr=496

**Comment by aeplay** [comment]
Sorry @bensleveritt I should document this somewhere but the homepage was a separate workspace on purpose, so you don't have to build it to build the packages - hope you didn't spend too much effort on it

**Comment by bensleveritt** [comment]
Didn’t spend any time on it, but I raised it because ‘turbo build’ includes the homepage package, which fails the whole build because homepage hasn’t been installed yet. A better fix is to exclude homepage from turbo's build dependencies

**Pull request closed without merging**
