### PR TITLE
WIP: Add code standards

### LINKED ISSUE #571: Enforce coding standards

### PR DESCRIPTION
**Pull request by bensleveritt**
Updates the root-level prettier config. Addresses #571

### CODE REVIEW

**Comment by trishalim** [comment]
FYI if you copy the branch name from Linear, it connects the PR with the issue, then closes the issue once the PR is merged 
image

**Comment by aeplay** [comment]
(I want to see how this interacts with the biggest concurrent PRs before proceeding, will do some tests)

**Comment by gdorsi** [comment]
**suggestion:** have we considered to use [Biome](https://biomejs.dev/) for formatting?

Performance aside, I've found it easier to setup compared to prettier.

It comes with good guides on how to [configure CI](https://biomejs.dev/recipes/continuous-integration/) and [git hooks](https://biomejs.dev/recipes/git-hooks/)

We may also use it for linting, but don't have so much experience there.

**Comment by bensleveritt** [comment]
> **suggestion:** have we considered to use [Biome](https://biomejs.dev/) for formatting?
> 
> Performance aside, I've found it easier to setup compared to prettier.
> 
> It comes with good guides on how to [configure CI](https://biomejs.dev/recipes/continuous-integration/) and [git hooks](https://biomejs.dev/recipes/git-hooks/)
> 
> We may also use it for linting, but don't have so much experience there.

Holy moly, if those claims are true...

I'll look into it, thanks for the heads up @gdorsi

**Pull request closed without merging**
