### PR TITLE
Redesign diagrams

### PR DESCRIPTION
**Pull request by trishalim**

### CODE REVIEW

**Comment by trishalim** [comment]
@aeplay I am still working on the illustration for the right hand side. Up to you if you wanna merge this or wait.

**Comment by aeplay** [comment]
Happy to merge this already btw but dark mode bold type is a bit broken for me

**Comment by trishalim** [comment]
@aeplay totally forgot, sorry! 🙈

**Comment by trishalim** [comment]
@aeplay dark mode done

**Pull request merged**
